### ISSUE TITLE
[Bug] `pi-spin` class not working after v7

### ISSUE THREAD

**Issue by Raphzor** [primefaces/primeicons#1159]
## Description
After v7.0.0 update, the `pi-spin` class is no longer working with Angular, not even on PrimeNG's documentation - [link](https://primeng.org/icons#spin).

- Tested on multiple browsers (Edge, Safari, Chrome)
- Tested on Mac and Windows
- Tested on a new blank project, with single dep from Primeicons
- Documentation from previous PrimNG version (v16.9.8-lts) still works - [link](https://www.primefaces.org/primeng-v16-lts/icons#spin)

**Comment by sslobodian-iqmessenger** [comment]
Same. To reproduce the issue turn off this option on Windows:
![image](https://github.com/user-attachments/assets/5519ffc1-49e0-445f-b026-ad9673972bd4)
Seems like it was done intentionally:
![image](https://github.com/user-attachments/assets/5d12ff2e-df98-4479-a9f8-6dedf5d2fe68)

**Comment by koesper** [comment]
There probably is a reason why they did it, and it actually is quite cool, but i prefer to have control over this little animation, since we use it to convey an actual meaning to the user.  
otherwise, it might be best to just hide the entire icon, instead of making it static?
(perhaps only for pi-spinner & pi-cog?)

```scss
@media (prefers-reduced-motion: reduce) {
   .pi-spin.pi-spinner,   .pi-spin.pi-cog  {
      visibility: hidden;
   }
}
```


but for now, I just added this workaround:
just add the original animation back in:

```scss
@media (prefers-reduced-motion: reduce) {
   .pi-spin {
       -webkit-animation: fa-spin 2s infinite linear !important;
       animation: fa-spin 2s infinite linear !important;
   }
}
```
